# Generated by Django 4.1.1 on 2023-02-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=45)),
                ('todo_description', models.TextField()),
                ('todo_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('todo_time', models.TimeField()),
            ],
        ),
    ]
